service: analytics

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2
  timeout: 30
  environment: ${file(./env.yml)}
  vpc:
    securityGroupIds:
      - 'sg-09b7d9888c893594d'
    subnetIds:
      - 'subnet-08c1aacead6928c9f'
      - 'subnet-076b9627be0729a38'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  graphql:
    warmup: true
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: '*'
            headers:
              - sessiontoken
              - Content-Type
            allowCredentials: false
      - http:
          path: graphql
          method: get
          cors:
            origin: '*'
            headers:
              - sessiontoken
              - Content-Type
            allowCredentials: false

custom:
  serverless-offline:
    port: 4000
  webpack:
      webpackConfig: ./webpack.config.js
      includeModules:
        forceInclude:
          - pg

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
